# Contains all core services that can be used for core and extension development.
services:

  # You can get the current organization and domain from this service, based on request information (like the path).
  united.cms.manager:
    class: UnitedCMS\CoreBundle\Service\UnitedCMSManager
    arguments: ['@doctrine.orm.entity_manager', '@request_stack']
    public: true


  # You can get all registered field types from this service and validate field settings and field data.
  united.cms.field_type_manager:
    class: UnitedCMS\CoreBundle\Field\FieldTypeManager
    public: true


  # You can get all registered view types from this service.
  united.cms.view_type_manager:
    class: UnitedCMS\CoreBundle\View\ViewTypeManager
    arguments: ['@router.default']
    public: true


  # Parses and serializes a domain object. This service is used to create a domain object from the JSON definition.
  united.cms.domain_definition_parser:
    class: UnitedCMS\CoreBundle\Service\DomainDefinitionParser
    arguments: ['@jms_serializer', '@validator']
    public: true


  # The fieldable form builder allows you to build content and setting forms based on the defined contentType / settingType fields.
  united.cms.fieldable_form_builder:
    class: UnitedCMS\CoreBundle\Form\FieldableFormBuilder
    arguments: ['@form.factory', '@united.cms.field_type_manager']
    public: true