language: php

# because we need to install mysql 5.7 first
sudo: required
dist: trusty
os: linux

matrix:
    include:
        - php: 7.1
        - php: 7.2
        - php: 7.1
          env: coverage=true

    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache/files

services:
  - mysql

env:
  global:
    - MYSQL_NAME=united_core_test
    - MYSQL_USER=root

before_install:
  - composer self-update
  - mysql -e 'CREATE DATABASE united_core_test;'

install:
  - composer install

before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql -e 'set global max_connections = 500;'
  - |
    if [[ $coverage ]]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter
      ./cc-test-reporter before-build
    fi

script:
  - |
    if [[ $coverage ]]; then
      phpunit --coverage-clover clover.xml
    else
      phpunit
    fi

after_success:
  - |
    if [[ $coverage ]]; then
      ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT
    fi